# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Deploy Python To IBM CF

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and publish
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: myorg/myrepository
        tags: latest
    - name: Deploy to IBM CF
      uses: citizen-of-planet-earth/cf-cli-action@v1
      with:
        cf_api: https://api.eu-gb.cf.cloud.ibm.com
        cf_username: ${{ secrets.CF_USER }}
        cf_password: ${{ secrets.CF_PASSWORD }}
        cf_org: ${{ secrets.CF_USER }}
        cf_space: dev
        command: push -f deploy/cf/manifest.yml
